version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      #Lambda deploy reference
      #https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html
      #Build spec reference
      #https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
      # Package SAM template1
      - sam package --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged.yaml
      # Deploy packaged SAM template
      #- sam deploy --template-file packaged.yaml --stack-name test --capabilities CAPABILITY_IAM  
artifacts:
  files:
    - packaged.yaml